# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # Runs lint and unit tests
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.5'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        make install
    - name: Install Linters
      run: pip install pylint
    - name: Run Linters
      run: make lint
    - name: Run Makefile test
      run: make unit
